# Generated by Django 4.0.4 on 2022-04-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_has_item_item_is_requested_alter_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
    ]
